@orgId = 110251487

### Create org

POST http://localhost:8080/organisation
Content-Type: application/json

{
  "name":"test1"
}

### List orgs

GET http://localhost:8080/organisation/list

### Get org

GET http://localhost:8080/organisation/{{ orgId }}

### Create earmarking

POST http://localhost:8080/organisation/{{ orgId }}/earmarking
Content-Type: application/json

{
  "name":"proj1"
}

### List earmarkings

GET http://localhost:8080/organisation/{{ orgId }}/earmarking/list

### Add account

POST http://localhost:8080/organisation/{{ orgId }}/account
Content-Type: application/json

{
  "name":"acc1",
  "balance":0
}

### List accounts

GET http://localhost:8080/organisation/{{ orgId }}/account/list