name: SonarQube CI

env:
  NEXT_PUBLIC_API_URL: http://localhost:8080

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1
      - name: Run tests
        working-directory: backend
        run: sbt -v jacoco

      - name: Install & test frontend
        run: |
          cd frontend
          npm ci
          npm run test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
